/* eslint-disable */
// AUTO-GENERATED by scripts/extract-prop-tables.mjs - do not edit by hand.
// Every prop each mockup accepts, lifted from the prop tables in the API docs
// so the explorer's inspector can show the whole surface, not just the parts
// it has a control for.

export interface PropDoc {
  name: string
  type: string
  default: string
  description: string
}

/** Props every mockup accepts, whatever it renders. */
export const SHARED_PROPS: PropDoc[] = [
    {"name":"children","type":"ReactNode","default":"-","description":"Screen content: any React node, iframe, or video."},
    {"name":"float","type":"boolean","default":"false","description":"Gentle floating idle animation for the device."},
    {"name":"position","type":"r3f transforms","default":"-","description":"Pose the device on the stage - transforms flow straight through to the device group (<GalaxyMockup rotation={[0, -0.25, 0]}>)."},
    {"name":"rotation","type":"r3f transforms","default":"-","description":"Pose the device on the stage - transforms flow straight through to the device group (<GalaxyMockup rotation={[0, -0.25, 0]}>)."},
    {"name":"scale","type":"r3f transforms","default":"-","description":"Pose the device on the stage - transforms flow straight through to the device group (<GalaxyMockup rotation={[0, -0.25, 0]}>)."},
    {"name":"resolution","type":"number","default":"per device","description":"CSS pixel width of the virtual display; height follows the panel aspect. See The virtual display."},
    {"name":"surfaceBackground","type":"string","default":"'#000000'","description":"CSS background painted behind your content, under whatever you render. See Surface background."},
    {"name":"surfaceStyle","type":"CSSProperties","default":"-","description":"Extra styles merged onto the screen wrapper (for example a custom fontFamily)."},
    {"name":"controls","type":"boolean","default":"true","description":"Drag-to-rotate controls with the axis fixed at the stage center (pan is always disabled). Vertical rotation stays within the classic orbit clamp by default."},
    {"name":"autoRotate","type":"boolean | number","default":"false","description":"Slowly spin the camera around the device. true is one revolution a minute; a number multiplies that (autoRotate={2} twice as fast, autoRotate={0.5} half). Held still under reduced motion."},
    {"name":"zoom","type":"boolean","default":"false","description":"Pinch zoom on touch, scroll-wheel zoom on desktop, plus overlay +/− buttons. Off by default so embedded mockups never hijack page scroll; on, the canvas owns two-finger gestures."},
    {"name":"fullscreen","type":"boolean","default":"false","description":"Adds an overlay button that expands the mockup to fill the screen via the Fullscreen API (and collapses it back). Off by default."},
    {"name":"shadows","type":"boolean","default":"true","description":"Soft contact shadow under the device."},
    {"name":"background","type":"string","default":"-","description":"CSS background of the canvas (color, gradient, or image). Transparent when unset - that is what the checkerboard behind each page's first example is showing through."},
    {"name":"camera","type":"r3f camera","default":"[0, 0.5, 7.4], fov 40","description":"Override the default camera."},
    {"name":"className","type":"-","default":"-","description":"Forwarded to the canvas wrapper."},
    {"name":"style","type":"-","default":"-","description":"Forwarded to the canvas wrapper."},
  ]

/** Object-specific props, by component name. */
export const COMPONENT_PROPS: Record<string, PropDoc[]> = {
  "GalaxyMockup": [
    {"name":"variant","type":"'s26' | 's26ultra'","default":"'s26'","description":"Which Galaxy device: true relative sizes, per-model cameras (S26 triple-lens pill island, Ultra large proud rings + tele column and S Pen silo), and logical resolutions."},
    {"name":"orientation","type":"'portrait' | 'landscape'","default":"'portrait'","description":"Landscape lays the device on its side and swaps the virtual display (for example 780×360 on the S26) with upright content."},
    {"name":"statusBar","type":"boolean | StatusBarContent","default":"false","description":"Draw the system status bar across the top of the screen. true gives the platform's defaults - One UI's, with the clock flush left and the meters at the right inset, clearing the punch hole; an object sets the clock, the meters and the ink ({{ time: '14:05', battery: 0.42, batteryPercent: true, color: '#1c1c1e' }}). It is placed from this device's own camera cutout and logical grid, so it lines up with the hardware on every variant. See Status bar."},
    {"name":"color","type":"string","default":"'#101216'","description":"Back panel. Takes a retail colorway id from GALAXY_COLORWAYS - S26 navy, cobaltviolet, icyblue, mint, silvershadow; Ultra titaniumsilverblue, titaniumblack, titaniumgray, titaniumwhitesilver - which brings that model's measured metal frame with it, or any CSS color for a custom finish - the frame is then derived from it."},
    {"name":"resolution","type":"number","default":"per variant","description":"CSS pixel width of the virtual display; height follows the panel aspect (360 gives 360×780 on the S26)."},
  ],
  "IPhoneMockup": [
    {"name":"variant","type":"'17' | 'air' | 'pro' | 'promax'","default":"'17'","description":"Which iPhone 17 family device: 17 (two-lens pill), air (ultra-thin, single-lens bar), pro and promax (full-width plateau, flash + LiDAR)."},
    {"name":"orientation","type":"'portrait' | 'landscape'","default":"'portrait'","description":"Landscape lays the device on its side and swaps the virtual display (for example 874×402 on the 17) with upright content."},
    {"name":"statusBar","type":"boolean | StatusBarContent","default":"false","description":"Draw the system status bar across the top of the screen. true gives the platform's defaults - iOS's, with the clock centred in the ear left of the Dynamic Island and the meters in the ear right of it; an object sets the clock, the meters and the ink ({{ time: '14:05', battery: 0.42, batteryPercent: true, color: '#1c1c1e' }}). It is placed from this device's own camera cutout and logical grid, so it lines up with the hardware on every variant. See Status bar."},
    {"name":"resolution","type":"number","default":"per variant","description":"Defaults to the variant's point grid: 402×874 (17, pro), 420×912 (air), 440×956 (promax)."},
    {"name":"color","type":"string","default":"'#1a1c20'","description":"Back glass. Takes a retail colorway id from IPHONE_COLORWAYS - 17 black, white, lavender, mistblue, sage; Air spaceblack, cloudwhite, lightgold, skyblue; Pro/Pro Max silver, cosmicorange, deepblue - which brings that model's measured chassis rail with it, or any CSS color - the rail is then derived from it."},
  ],
  "FoldMockup": [
    {"name":"variant","type":"'fold7' | 'fold8' | 'fold8ultra'","default":"'fold7'","description":"Which Galaxy Z Fold to render. fold7 and fold8ultra share the tall book chassis; fold8 is the generation's wide form factor, opening into a landscape 4:3 tablet."},
    {"name":"openAngle","type":"boolean | number","default":"true","description":"How far the book is open. true is the unfolded tablet (content on the big inner display, with a center crease), false the folded candy-bar (content on the cover display, rear camera pill showing). A number is degrees (0 = shut, 180 = flat) and renders the real Flex Mode book pose: the panels pivot around the Armor FlexHinge while its rounded spine (with the SAMSUNG engraving) stays tangent to both back shells, wrapping the fold at every angle, and your content bends across the crease on two composited planes. The pose is continuous: every angle renders its own pose, and only the extremes hand over to the dedicated folded (~0°) and flat (180°) poses, which draw the crease as one seamless screen."},
    {"name":"orientation","type":"'portrait' | 'landscape'","default":"'portrait'","description":"Rotates the device a quarter turn and swaps the virtual display with upright content. On the fold7 and fold8ultra that lays the tablet on its side; on the natively landscape fold8 it stands it upright."},
    {"name":"statusBar","type":"boolean | StatusBarContent","default":"false","description":"Draw the system status bar across the top of the screen. true gives the platform's defaults - One UI's, on the cover screen and on the inner display alike, clearing whichever punch hole is showing - including the inner display's off-centre one; an object sets the clock, the meters and the ink ({{ time: '14:05', battery: 0.42, batteryPercent: true, color: '#1c1c1e' }}). It is placed from this device's own camera cutout and logical grid, so it lines up with the hardware on every variant. See Status bar."},
    {"name":"color","type":"string","default":"'#3a3d42'","description":"Back panel. Takes a retail colorway id from FOLD_COLORWAYS[variant], which brings that model's frame and hinge with it, or any CSS color - the metal is then derived from it."},
    {"name":"resolution","type":"number","default":"per state","description":"CSS pixel width of the active display; height follows the panel aspect. Defaults to the device's own logical grid for whichever screen is showing - see the device table."},
  ],
  "FlipMockup": [
    {"name":"variant","type":"'flip7' | 'flip8'","default":"'flip7'","description":"Which Galaxy Z Flip to render. The Flip 8 is a hair bigger and thinner, its main display grown to 6.9″ on the same panel grid; the cover screen is unchanged."},
    {"name":"openAngle","type":"boolean | number","default":"true","description":"How far the clamshell is open. true is the unfolded tall phone (content on the main display), false the folded compact (content on the nearly square cover display, lens rings overlaid like cutouts). A number is degrees (0 = shut, 180 = flat) and renders the real Flex Mode pose: the halves pivot around the Armor FlexHinge while its glossy spine band (with the SAMSUNG engraving) rolls into the gap, and your content bends across the fold on two composited planes. The pose is continuous: every angle renders its own pose, and only the extremes hand over to the dedicated folded (~0°) and flat (180°) poses, which draw the crease as one seamless screen."},
    {"name":"orientation","type":"'portrait' | 'landscape'","default":"'portrait'","description":"Landscape lays the device on its side and swaps the virtual display with upright content."},
    {"name":"statusBar","type":"boolean | StatusBarContent","default":"false","description":"Draw the system status bar across the top of the screen. true gives the platform's defaults - One UI's, on the main display; the cover screen has its own clock and no status bar, so it draws none; an object sets the clock, the meters and the ink ({{ time: '14:05', battery: 0.42, batteryPercent: true, color: '#1c1c1e' }}). It is placed from this device's own camera cutout and logical grid, so it lines up with the hardware on every variant. See Status bar."},
    {"name":"color","type":"string","default":"'#22252b'","description":"Back glass / cover. Takes a retail colorway id from FLIP_COLORWAYS[variant], which brings that model's frame and hinge band with it, or any CSS color - the metal is then derived from it."},
    {"name":"resolution","type":"number","default":"per state","description":"CSS pixel width of the active display; height follows the panel aspect."},
  ],
  "LaptopMockup": [
    {"name":"variant","type":"'air13' | 'air15' | 'pro14' | 'pro16'","default":"'air13'","description":"MacBook Air 13\"/15\" or MacBook Pro 14\"/16\" - true relative sizes, per-model ports, feet, speaker grilles and notch."},
    {"name":"color","type":"string","default":"'#e3e4e6'","description":"Aluminum finish. Takes a retail colorway id from LAPTOP_COLORWAYS - Airs silver, starlight, midnight, skyblue; Pros spaceblack, silver - or any CSS color."},
    {"name":"openAngle","type":"number","default":"110","description":"Lid angle in degrees between deck and screen (90 is upright)."},
    {"name":"resolution","type":"number","default":"per variant","description":"Virtual display width - each variant defaults to its real scaled desktop: 1280×832 (air13), 1440×932 (air15), 1512×982 (pro14), 1728×1117 (pro16) - so desktop breakpoints apply."},
  ],
  "IPadMockup": [
    {"name":"variant","type":"'ipadpro13' | 'ipadpro11' | 'ipadair13' | 'ipadair11' | 'ipad11'","default":"'ipadpro13'","description":"Which iPad: Pro 13\"/11\" (camera pod, Pencil strip, Face ID), Air 13\"/11\" (single lens, Touch ID top button), or the A16 iPad (single lens, edge Smart Connector)."},
    {"name":"orientation","type":"'portrait' | 'landscape'","default":"'portrait'","description":"Landscape lays the tablet on its side and swaps the virtual display (for example 1376×1032 on the 13\" Pro) with upright content."},
    {"name":"statusBar","type":"boolean | StatusBarContent","default":"false","description":"Draw the system status bar across the top of the screen. true gives the platform's defaults - iPadOS's, a 24pt strip with the clock at the leading inset and the meters at the trailing one; an object sets the clock, the meters and the ink ({{ time: '14:05', battery: 0.42, batteryPercent: true, color: '#1c1c1e' }}). It is placed from this device's own camera cutout and logical grid, so it lines up with the hardware on every variant. See Status bar."},
    {"name":"resolution","type":"number","default":"per variant","description":"Defaults to the variant's logical grid: 1032×1376 (ipadpro13), 834×1210 (ipadpro11), 1024×1366 (ipadair13), 820×1180 (ipadair11, ipad11)."},
    {"name":"color","type":"string","default":"per variant","description":"Body color. Takes a retail colorway id from IPAD_COLORWAYS - Pro spaceblack/silver, Air spacegray/starlight/purple/blue, iPad silver/blue/pink/yellow - or any CSS color."},
  ],
  "GalaxyTabMockup": [
    {"name":"variant","type":"'tabs11' | 'tabs11ultra'","default":"'tabs11'","description":"Tab S11 (single camera ring) or Tab S11 Ultra (dual rings, 14.6\" panel with the U-shaped notch)."},
    {"name":"orientation","type":"'portrait' | 'landscape'","default":"'portrait'","description":"Landscape lays the tablet on its side and swaps the virtual display with upright content."},
    {"name":"statusBar","type":"boolean | StatusBarContent","default":"false","description":"Draw the system status bar across the top of the screen. true gives the platform's defaults - One UI's tablet bar, with the clock at the leading inset and the meters at the trailing one; an object sets the clock, the meters and the ink ({{ time: '14:05', battery: 0.42, batteryPercent: true, color: '#1c1c1e' }}). It is placed from this device's own camera cutout and logical grid, so it lines up with the hardware on every variant. See Status bar."},
    {"name":"resolution","type":"number","default":"per variant","description":"Defaults to the variant's logical grid: 800×1280 (tabs11), 924×1480 (tabs11ultra)."},
    {"name":"color","type":"string","default":"per variant","description":"Body color. Takes a retail colorway id from GALAXY_TAB_COLORWAYS (gray, silver) or any CSS color."},
  ],
  "AppleWatchMockup": [
    {"name":"variant","type":"'series11'","default":"'series11'","description":"Which Apple Watch to render."},
    {"name":"color","type":"string","default":"'#1c1d21'","description":"Aluminium case. Takes a retail colorway id from APPLE_WATCH_COLORWAYS (jetblack, spacegray, rosegold, silver) or any CSS color."},
    {"name":"bandColor","type":"string","default":"'#2a2c31'","description":"Solo Loop colorway."},
    {"name":"resolution","type":"number","default":"208","description":"Virtual display width - 208 is the watch's own point grid, so watchOS-sized layouts apply."},
  ],
  "GalaxyWatchMockup": [
    {"name":"variant","type":"'watch8' | 'watch9' | 'watchultra2'","default":"'watch8'","description":"Which Galaxy Watch to render. The Watch 9 is the Watch 8's case with the generation's internals; the Watch Ultra 2 is the 47 mm titanium squircle."},
    {"name":"color","type":"string","default":"'#1c1d21'","description":"Case. Takes a retail colorway id from GALAXY_WATCH_COLORWAYS[variant] (graphite/silver on the 44 mm models, titaniumsilver/titaniumgray on the Ultra 2) or any CSS color."},
    {"name":"bandColor","type":"string","default":"'#2a2c31'","description":"Strap colorway (fluoroelastomer)."},
    {"name":"bandOpen","type":"boolean","default":"false","description":"Lay the band out unbuckled and flat instead of wearing it."},
    {"name":"resolution","type":"number","default":"per variant","description":"Virtual display width - each model's own dp grid (240 on the 44 mm models, 249 on the Ultra 2), and the display is round, so give your face a border-radius: 50% root (or design edge-to-edge and let the crystal mask it)."},
  ],
  "StudioDisplayMockup": [
    {"name":"color","type":"string","default":"'#c8cbd0'","description":"Aluminum enclosure and stand. Takes a retail colorway id from STUDIO_DISPLAY_COLORWAYS (silver) or any CSS color for a custom finish."},
    {"name":"resolution","type":"number","default":"2560","description":"CSS pixel width of the virtual display; height follows the 16:9 panel. The default is the display's own logical grid - 2560×1440, which is 5120×2880 at 2x - so desktop breakpoints apply."},
  ],
  "BookMockup": [
    {"name":"size","type":"{ width?, height?, thickness? }","default":"156×234×27","description":"Physical trim in mm - e.g. { width: 216, height: 279 } for a letter-size art book, { thickness: 45 } for a fat novel."},
    {"name":"color","type":"string","default":"'#1f3a5f'","description":"Cloth color: spine, back board, and board edges."},
    {"name":"pageColor","type":"string","default":"'#f4eede'","description":"Paper color of the page block edges."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind your cover content."},
    {"name":"resolution","type":"number","default":"480","description":"Virtual cover width in CSS px; height follows the board aspect."},
  ],
  "MagazineMockup": [
    {"name":"size","type":"{ width?, height?, thickness? }","default":"216×279×6","description":"Physical trim in mm - e.g. { width: 210, height: 297 } for A4, { thickness: 12 } for a thick issue."},
    {"name":"pageColor","type":"string","default":"'#fbfaf7'","description":"Paper color of the trimmed page edges."},
    {"name":"backColor","type":"string","default":"'#e9e7e2'","description":"Back cover and spine-wrap color."},
    {"name":"glossy","type":"boolean","default":"false","description":"Coated gloss stock: a soft diagonal sheen over the cover art and a clearcoat on the spine and back. Off = matte paper."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind your cover content."},
    {"name":"resolution","type":"number","default":"480","description":"Virtual cover width in CSS px; height follows the trim aspect."},
  ],
  "BrochureMockup": [
    {"name":"size","type":"{ width?, height? }","default":"93×216","description":"One panel's physical size in mm - e.g. { width: 99, height: 210 } for an A4 tri-fold."},
    {"name":"foldAngle","type":"number","default":"24","description":"Zig-zag fold angle in degrees. 0 lays the sheet out flat."},
    {"name":"color","type":"string","default":"'#f5f4f0'","description":"Stock color of unprinted faces and paper edges."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind each panel's content."},
    {"name":"resolution","type":"number","default":"360","description":"Virtual width of one panel in CSS px; height follows the panel aspect."},
  ],
  "BusinessCardMockup": [
    {"name":"color","type":"string","default":"'#f7f6f2'","description":"Stock color: the faces' base and unprinted back."},
    {"name":"edgeColor","type":"string","default":"stock color","description":"Painted-edge color - the bright seam that says \"32 pt\"."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind each face's content."},
    {"name":"resolution","type":"number","default":"520","description":"Virtual face width in CSS px (~150 dpi); height follows the card aspect."},
  ],
  "IDCardMockup": [
    {"name":"color","type":"string","default":"'#f4f5f7'","description":"Card stock: the edges and the inside of the punched slot."},
    {"name":"lanyardColor","type":"string","default":"'#b3223a'","description":"Woven strap color (lanyards come in saturated solids)."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind each face's content."},
    {"name":"resolution","type":"number","default":"420","description":"Virtual face width in CSS px; height follows the full card."},
  ],
  "GreetingCardMockup": [
    {"name":"openAngle","type":"number","default":"65","description":"Angle between the panels (display sweet spot is 60–75)."},
    {"name":"color","type":"string","default":"'#f6f3ec'","description":"Card stock: edges and unprinted faces."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind each printed face."},
    {"name":"resolution","type":"number","default":"380","description":"Virtual panel width in CSS px; height follows the A7 panel."},
  ],
  "PosterFrameMockup": [
    {"name":"size","type":"{ width?, height? }","default":"457×610","description":"Physical sheet in mm - e.g. { width: 610, height: 914 } for 24\"×36\", { width: 594, height: 841 } for A1."},
    {"name":"color","type":"string","default":"'#22262e'","description":"Frame molding color."},
    {"name":"mat","type":"boolean | string","default":"false","description":"Mount the art behind a 2.5\" gallery matboard. true cuts it from the default #f6f3ec museum board; a CSS color cuts it from that stock instead, so mat=\"#1d1f24\" is a dark mount."},
    {"name":"glazing","type":"boolean","default":"true","description":"Soft acrylic sheen over the art."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind your poster content."},
    {"name":"resolution","type":"number","default":"540","description":"Virtual art width in CSS px; height follows its aspect."},
  ],
  "ProductBoxMockup": [
    {"name":"size","type":"{ width, height, depth }","default":"190×265×55","description":"Real size in millimeters. The longest edge normalizes to the stage, so any size fills the camera at true proportions."},
    {"name":"color","type":"string","default":"'#f4f1ea'","description":"Carton stock: unprinted panels and fold edges."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind each printed panel."},
    {"name":"resolution","type":"number","default":"480","description":"Virtual front-panel width in CSS px; other panels share its dpi."},
  ],
  "MailerBoxMockup": [
    {"name":"size","type":"{ width, height, depth }","default":"350×120×250","description":"Real size in millimeters. The longest edge normalizes to the stage, so any size fills the camera at true proportions."},
    {"name":"color","type":"string","default":"'#b5915f'","description":"Corrugated stock. Kraft by default; try white or a brand dip."},
    {"name":"tapeColor","type":"string","default":"'rgba(168, 127, 79, 0.82)'","description":"Packing tape color."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind each printed panel."},
    {"name":"resolution","type":"number","default":"520","description":"Virtual top panel width in CSS px; other panels share its dpi."},
  ],
  "MilkCartonMockup": [
    {"name":"size","type":"{ width, height, depth }","default":"95×241×95","description":"Real size in millimeters, height measured over the roof and fin. The longest edge normalizes to the stage, so any size fills the camera at true proportions."},
    {"name":"color","type":"string","default":"'#f4f3ef'","description":"Board color. Poly-coated white by default; try a brand dip or kraft."},
    {"name":"capColor","type":"string","default":"'#d7dbdf'","description":"Screw cap color."},
    {"name":"cap","type":"boolean","default":"true","description":"Render the screw cap. Off gives the older pull-open spout carton."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind each printed panel."},
    {"name":"resolution","type":"number","default":"420","description":"Virtual front panel width in CSS px; other panels share its dpi."},
  ],
  "ShoppingBagMockup": [
    {"name":"size","type":"{ width, height, depth }","default":"320×420×140","description":"Real size in millimeters. The longest edge normalizes to the stage, so any size fills the camera at true proportions."},
    {"name":"color","type":"string","default":"'#c19a6b'","description":"Bag stock. Kraft by default; try gloss white or a brand dip."},
    {"name":"handleColor","type":"string","default":"'#7d6142'","description":"Rope handle color."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind each printed face."},
    {"name":"resolution","type":"number","default":"460","description":"Virtual front face width in CSS px; height follows the bag."},
  ],
  "CustomPanelMockup": [
    {"name":"size","type":"{ width, height, thickness? }","default":"required","description":"Panel size in millimeters. thickness defaults to 5."},
    {"name":"color","type":"string","default":"'#f2f1ed'","description":"Stock color: edges, and the back when unprinted."},
    {"name":"cornerRadius","type":"number","default":"2","description":"Corner rounding in millimeters."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind each printed face."},
    {"name":"resolution","type":"number","default":"560","description":"Virtual front face width in CSS px."},
  ],
  "CustomBoxMockup": [
    {"name":"size","type":"{ width, height, depth }","default":"required","description":"Box size in millimeters."},
    {"name":"color","type":"string","default":"'#e8e5df'","description":"Stock color for unprinted faces."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind each printed face."},
    {"name":"resolution","type":"number","default":"560","description":"Virtual front face width in CSS px; all faces share its dpi."},
  ],
  "VinylRecordMockup": [
    {"name":"vinylColor","type":"string","default":"'#0b0b0d'","description":"Disc color. Classic black; try pressing colors."},
    {"name":"color","type":"string","default":"'#f2efe8'","description":"Jacket stock (edges and unprinted faces)."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind cover, back and label."},
    {"name":"resolution","type":"number","default":"520","description":"Virtual cover width in CSS px; the label shares its dpi."},
  ],
  "RollupBannerMockup": [
    {"name":"size","type":"{ width?, height? }","default":"850×2000","description":"Physical graphic in mm - e.g. { width: 1000 } for the wide stand. The cassette resizes with it."},
    {"name":"color","type":"string","default":"'#b9bdc4'","description":"Hardware color: cassette, feet, pole, top rail."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind your graphic content."},
    {"name":"resolution","type":"number","default":"420","description":"Virtual graphic width in CSS px; height follows the 850×2000 sheet."},
  ],
  "AFrameSignMockup": [
    {"name":"color","type":"string","default":"'#4a3826'","description":"Frame color - dark-stained wood by default."},
    {"name":"surfaceBackground","type":"string","default":"'#20241f'","description":"CSS background behind each panel (chalkboard black)."},
    {"name":"resolution","type":"number","default":"420","description":"Virtual face width in CSS px; height follows the panel."},
  ],
  "BusShelterMockup": [
    {"name":"color","type":"string","default":"'#2f333a'","description":"Street-furniture steel: roof, posts, frames, bench supports."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind the poster (backlit white)."},
    {"name":"resolution","type":"number","default":"480","description":"Virtual poster width in CSS px; height follows the 6-sheet."},
  ],
  "DOOHTotemMockup": [
    {"name":"size","type":"{ width?, height? }","default":"1300×2800","description":"Physical enclosure in mm - e.g. { width: 1100, height: 2500 } for a slimmer kiosk. The glass and display scale with the cabinet."},
    {"name":"color","type":"string","default":"'#2f333a'","description":"Enclosure colorway."},
    {"name":"resolution","type":"number","default":"540","description":"Virtual display width; 540 gives 540×960 (a 1080×1920 grid at 2x)."},
  ],
  "BillboardMockup": [
    {"name":"color","type":"string","default":"'#2c313a'","description":"Steel color: panel, apron, pole, catwalk, and fixtures."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind your face content."},
    {"name":"resolution","type":"number","default":"1200","description":"Virtual face width in CSS px; height follows the 14:48 bulletin."},
  ],
  "StorefrontMockup": [
    {"name":"color","type":"string","default":"'#2e4638'","description":"Shopfront paint: fascia surrounds, frames, door, stall risers."},
    {"name":"windowColor","type":"string","default":"'#5a6d75'","description":"Glazing color - every display pane, the transom lights and the door leaf. Tints the reflection rather than painting the pane flat, so the glass keeps its mirror finish. Try '#6b5a44' bronze, '#4d6b60' green, or something darker for a shop that reads as closed."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind sign and poster content."},
    {"name":"resolution","type":"number","default":"800","description":"Virtual fascia sign width in CSS px. Window panes use fixed widths (~420–480 px); override per pane with each slot's resolution."},
  ],
  "BusMockup": [
    {"name":"color","type":"string","default":"'#eef0f2'","description":"Body paint. Transit fleets are usually white or silver."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind your ad content."},
    {"name":"coverage","type":"'panel' | 'full' | 'perforated'","default":"'panel'","description":"How much of the bus the live surfaces cover. 'full' turns the entire side elevations and the tail live, carving the passenger glass out so it stays visible; 'perforated' runs the same wrap OVER that glass as perforated window film. Doors and the driver's window always stay clear."},
    {"name":"resolution","type":"number","default":"960 panel · 1920 full","description":"Virtual side-surface width in CSS px; the rear surface shares its dpi."},
  ],
  "VanMockup": [
    {"name":"color","type":"string","default":"'#eef0f2'","description":"Body paint. Wrap fleets are usually white."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind your wrap content."},
    {"name":"coverage","type":"'panel' | 'full' | 'perforated'","default":"'panel'","description":"'full' covers the entire side elevations AND the whole rear face - door edge to door edge - carving out the wheel arches and door glass, while the proud hardware (mirrors, handles, door track, cab-door shut lines) draws on top of the livery via per-pixel depth compositing, like hardware remounted over the vinyl. On the rear, every taillight lamp, the third brake light and the hinge knuckles are carved to a slim install margin. Both coverages keep the barn-door shut line visible through the wrap. 'perforated' is the same full wrap running OVER the cab door glass as perforated window film."},
    {"name":"resolution","type":"number","default":"900 panel · 1360 full","description":"Virtual side-wrap width in CSS px; the rear panel shares its dpi."},
  ],
  "SemiTrailerMockup": [
    {"name":"color","type":"string","default":"'#eef0f2'","description":"Box paint. Wrap trailers are usually white."},
    {"name":"skirtColor","type":"string","default":"matches color","description":"Side-skirt paint - the thin aero panels under the box."},
    {"name":"surfaceBackground","type":"string","default":"'#ffffff'","description":"CSS background behind your wrap content."},
    {"name":"resolution","type":"number","default":"1100","description":"Virtual side panel width in CSS px; the rear shares its dpi."},
  ],
  "TVSetMockup": [
    {"name":"variant","type":"'legs' | 'pedestal' | 'frame'","default":"'legs'","description":"Which design: splayed A-frame feet, a center pedestal, or the wall-hung picture-frame set."},
    {"name":"size","type":"number","default":"65","description":"Diagonal in inches, clamped to 32–98. Panel scales; bezels, ports and stand follow real product ratios."},
    {"name":"color","type":"string","default":"'#15171b'","description":"Enclosure colorway (frame, back, stand)."},
    {"name":"resolution","type":"number","default":"1920","description":"Virtual display width; 1920 gives 1920×1080."},
  ],
}
